### ISSUE TITLE
「AtCoder GUI」を追加

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderClans#7843]
https://github.com/TsuruNoTsurugi/atcoder-GUI

**Comment by KATO-Hiro** [comment]
macだとTkinterのモジュールがないとエラーが出る

```md
➜ python gui/main.py
Traceback (most recent call last):
  File "/Users/hiro/Documents/study/AtCoder/sample/gui/main.py", line 1, in <module>
    import tkinter
  File "/Users/hiro/.pyenv/versions/3.11.4/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
```
